### PR TITLE
Awaiting async function in async iterator

### PR DESCRIPTION
**Pull request by George-Payne**
- Allow awaiting within async iterators
  - Queue events and pull as needed
  - If no events in queue, wait for next event
  - Move to seperate SubscriptionItorator and return that in async iteration (for both subscription types)
- Add same test case for persistent subscriptions

### CODE REVIEW

**Comment by thomastoye** [comment]
Won't using a queue like this run the risk of running out of memory if the stream that is subscribed to is large and the async function takes long? I'm not seeing any backpressure. Would it be possible to access a readable stream from a subscription?

**Comment by George-Payne** [comment]
You're quite right, I've capped the length of the queue to be 10 by pausing and resuming the subscription.

**Comment by George-Payne** [comment]
> Would it be possible to access a readable stream from a subscription?

Looks like the correct way to do this, but I'll need to do more reading before I go about implementing it. I've opened an issue (#78) to track it.

**Comment by thomastoye** [comment]
I'm not sure if the GPRC stream are Node streams as well, but if they are, you may be able to simplify this, since Node readable streams are async iterables/have a `Symbol.asyncIterable` property.

**Comment by thomastoye** [comment]
Dropping by to let you know that this fixed my issue 👍

**Comment by George-Payne** [comment]
> I'm not sure if the GPRC stream are Node streams as well, but if they are, you may be able to simplify this, since Node readable streams are async iterables/have a `Symbol.asyncIterable` property.

I've moved it over to using streams, need to decide if / how we want to expose the stream directly. It might be that I replace `Subscription` with a stream, but it needs more thought. I'll keep this tracked in #78

**Review by YoEight — APPROVED** [review]

**Comment by thomastoye** [comment]
🎉 

@George-Payne / @hayley-jean Could you publish a new package version?

**Comment by George-Payne** [comment]
@thomastoye Just published `0.0.0-alpha.8`

**Pull request merged**
