### PR TITLE
increase test coverage for reconnection

### LINKED ISSUE #231: Increase coverage of testing for behaviour around node loss and reconnection
Reconnection tests currently only cover reads and writes. it would be good to expand them out to cover more apis , such as persistent subscriptions.

https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/src/__test__/connection/reconnect.test.ts

_Originally posted by @oskardudycz in https://github.com/EventStore/EventStore-Client-NodeJS/pull/220#discussion_r741920747_

### PR DESCRIPTION
**Pull request by Imanghvs**
Closes #231

### CODE REVIEW

**Comment by Imanghvs** [comment]
@George-Payne
May I ask you to review this? As a regular user of this package I'm really passionate to start making small contributions. If there's any problem with my PR please let me know. I would be happy to correct it.

**Comment by George-Payne** [comment]
Hi @Imanghvs, sorry for the slow response, I've been on paternity leave. I should have made sure someone else had alerts set up for the repo, must have forgotten, my apologies. 

I'll take a look at the PR shortly.

**Review by cdevarenne — APPROVED** [review]
Tests ran fine.

**Review by w1am — APPROVED** [review]
Awesome!

**Pull request merged**
